# Generated by Django 4.1 on 2025-09-09 15:05

import cinema.download_images
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="image",
            field=models.ImageField(
                null=True, upload_to=cinema.download_images.movie_image_path
            ),
        ),
    ]
